name: wge-build-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  engine-debug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        uses: docker://ghcr.io/iwas-coder/wge-builder
      - name: test
        uses: docker://ghcr.io/iwas-coder/wge-builder
        with:
          args: check
  engine-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        uses: docker://ghcr.io/iwas-coder/wge-builder
        with:
          args: RELEASE=1
      - name: test
        uses: docker://ghcr.io/iwas-coder/wge-builder
        with:
          args: RELEASE=1 check
