name: wge-cli-builder

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ github.workflow }}
  IMAGE_TAGS: latest ${{ github.sha }}
  REGISTRY: docker://ghcr.io/iwas-coder
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PWD: ${{ github.token }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: install-dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./cli/Containerfile
      - name: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PWD }}
          extra-args: |
            --disable-content-trust
