name: wge/cli/builder

on:
  push:
    branches: [master]
    paths: ['cli/Containerfile']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ github.workflow }}
  IMAGE_TAGS: latest ${{ github.sha }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PWD: ${{ github.token }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: install-dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./cli/Containerfile
          platforms: linux/amd64 linux/arm64/v8
      - name: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PWD }}
